### ISSUE TITLE
Invalid URL in default.md

### ISSUE THREAD

**Issue by singhayushh** [mindwebs/hf2020_cards#3]
**Where was the bug found?**
File name: default.md
File path: /pages/posts/default.md
Line No: In the last line, with the following text
`If you Want to do something more in these pages then have a look at the page by Ayushman`

**How to face this bug?**
Opening the files on Github

> Also, the file advanced_features.md does not compile the js tags added when viewed from the Github Web Interface

**Comment by ayushmanbt** [comment]
I have fixed the issue😅

**Comment by singhayushh** [comment]
Okay!
